Правда или действие (часть 1)
htmlacademy-javascript/1295903-kekstagram-25 pull request #7
Opened 2022-03-18 08:38 UTC by lezhnina-anna

2022-03-18 11:59 UTC, o-bender requested changes
Отлично!)

2022-03-18 11:59 UTC, o-bender commented on js/user-form.js
> +  const hashtags = value.split(' ');
давай лучше так: `value.toLowerCase().split(/\s+/)`

2022-03-18 11:59 UTC, o-bender commented on js/user-form.js
> +    if (!hashtags[i]) {
я так понимаю это что бы пустые строки отсеивать. если перейти на `value.split(' ')`, то эта секция и не нужна

2022-03-18 11:59 UTC, o-bender commented on js/user-form.js
> +      wasError = true;
а почему бы тут просто не делать `return false`?

2022-03-18 11:59 UTC, o-bender commented on js/user-form.js
> +    if (uniqueHashtags.indexOf(hashtags[i]) !== -1) {
мб проще будет так:
```
if (!hashtags.slice(i+1).includes(tag)) {
    return false;
}
```

2022-03-18 11:59 UTC, o-bender commented on js/user-form.js
> +  for (let i = 0; i < hashtags.length; i++) {
учитывая все последующие комменты, мб тут использовать for of?

2022-03-18 11:59 UTC, o-bender commented on js/user-form.js
> +  loadPhotoInput.addEventListener('change', () => {
давай без лишних обёрток. `loadPhotoInput.addEventListener('change', openForm)`

2022-03-18 11:59 UTC, o-bender commented on js/user-form.js
> +  userModalCloseElement.addEventListener('click', () => {
и тут тоже)

2022-03-20 12:48 UTC, lezhnina-anna commented on js/user-form.js
> +    if (uniqueHashtags.indexOf(hashtags[i]) !== -1) {
При замене цикла на for .. of у нас в цикле больше нет значения i, поэтому оставила дополнительный массив

2022-03-20 12:50 UTC, lezhnina-anna commented on js/user-form.js
> +    if (!hashtags[i]) {
Осталась проблема только если вся изначальная строка пустая, добавила проверку в самом начале функции

2022-03-20 18:38 UTC, merged